[tools]
lune = "lune-org/lune@0.8.9"
wally = "upliftgames/wally@0.3.2"
# rojo = "rojo-rbx/rojo@7.4.4"
# stylua = "johnnymorganz/stylua@0.20.0"
# Blink = "1Axen/Blink@0.14.1"
# selene = "kampfkarren/selene@0.27.1"
